language: c
sudo: required
before_install:
- sudo apt-get install gfortran make libfcgi-dev
script:
- make dart_cgi
deploy:
  provider: releases
  api_key:
    secure: RyN1Y/ppSLqEDeBEA8gSs5GuaGQIy7pCGATNt2dygYGkpMzMsqG7skLzMp5hQugEaxH5ZlVwhPSPPTIbkpH/USeUu+NSwZV+0GMeJ/fkecMhSyOIqmR/LvfY3iN7PT8/ksejr5lU0TQDTBAoG58wu16rxKC4w8qXuTIbr3pzzABfMCoricWlVSsk4JY6IhFNLul5/pU2JQ3z2d5+b4czXTiUim/GBsT0PmV7CTRkutTFKOeJnMgIfN8du0NNL0HjBO8r/3I0P3YvF9AuxS9ftbDS/ayzdB2Dk9pOpyBMaOp8gyqnCkNdoR/eS6rni/o8G004tRMuxanRQEN0DhKj3acjcPVJwTyWKI4cq3nohdpE0seZnWvY2xSGi4YvJoIck/8NModQjm02QtDCxuqv7ruUBrhsGBj2ySImi7c2S8P/PTPCeZzpVRZykee6UsgLn1+dQSd35+RecpdB8lx6GhjS1YdF8yvRCnPvbMV0iJG8SyFt2XX4TrlX1GBi9F8sO0aDIZCxAy4ocKMtDi1rnMW18fWw58ihsMB/FmWu+3NyVP4n2mHzCDyfUL51z3ywwEio5/R6dMJCy589BYx8Ya7sJftBIcAzGIFa8fR62qvp2oKZbrjClpsSVq3rkR58JJAK6V08CsvCWg0dIsYgA8eK3ag9yip8NBQZsj2Oyhg=
  file: dart_cgi
  skip_cleanup: true
  on:
    repo: szhilkin/fortran_cgi
